clean:
	\rm -f test_out.fd test_err test_Logger_log test_debug test_cfg_rewrite test_FileDict_rewrite.fd test_out2.fd test_out3.fd test_out4.fd test_err2 test_err3 test_err4 test_debug2 test_debug3 test_debug4 test_xrun* testFig.eps testFig.png test_F0.eps test_F0.png
